### ISSUE TITLE
Dev

### ISSUE THREAD

**Issue by mkz212** [homebridge-plugins/homebridge-virtual-device#51]
Dev

**Comment by mkz212** [comment]
@nanos @jandersonhill

I created this project, And it's actually ready. But I don't think I want to be the author of the plugin, I'd rather be such a helper. Anyone interested?

This is plugin such a dummy-switch or delay-switch but:
- these project are abandoned
- these project are accessory plugin (deprecated) and this is platform plugin
- this project offers more and fix bugs from these projects
- more in readme

**Comment by nanos** [comment]
Not me, sorry
